services:
  redis-init:
    container_name: redis-init
    image: redis:7.0
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    entrypoint:
      [
        '/bin/sh',
        '-c',
        'sleep 5 && redis-cli --cluster create redis-node-1:7001 redis-node-2:7002 redis-node-3:7003 --cluster-replicas 0 --cluster-yes',
      ]
    networks:
      - redis-network

  redis-node-1:
    container_name: redis-node-1
    image: redis:7.0
    command:
      [
        'redis-server',
        '--port',
        '7001',
        '--cluster-enabled',
        'yes',
        '--cluster-config-file',
        'nodes.conf',
        '--cluster-node-timeout',
        '5000',
        '--appendonly',
        'yes',
      ]
    ports:
      - '7001:7001'
    volumes:
      - redis-node-1-data:/data
      - ./scripts:/scripts:ro
    networks:
      - redis-network

  redis-node-2:
    container_name: redis-node-2
    image: redis:7.0
    command:
      [
        'redis-server',
        '--port',
        '7002',
        '--cluster-enabled',
        'yes',
        '--cluster-config-file',
        'nodes.conf',
        '--cluster-node-timeout',
        '5000',
        '--appendonly',
        'yes',
      ]
    ports:
      - '7002:7002'
    volumes:
      - redis-node-2-data:/data
    networks:
      - redis-network

  redis-node-3:
    container_name: redis-node-3
    image: redis:7.0
    command:
      [
        'redis-server',
        '--port',
        '7003',
        '--cluster-enabled',
        'yes',
        '--cluster-config-file',
        'nodes.conf',
        '--cluster-node-timeout',
        '5000',
        '--appendonly',
        'yes',
      ]
    ports:
      - '7003:7003'
    volumes:
      - redis-node-3-data:/data
    networks:
      - redis-network

volumes:
  redis-node-1-data:
    driver: local
  redis-node-2-data:
    driver: local
  redis-node-3-data:
    driver: local

networks:
  redis-network:
    external: true
